import type { Snippet } from './types'

// A port of the Obsidian LaTeX Suite default snippet set, plus a section of
// snippets for the mathbook class.  Edit or extend freely in the Snippets tab.

const greek: Record<string, string> = {
  '@a': 'alpha', '@b': 'beta', '@g': 'gamma', '@G': 'Gamma', '@d': 'delta', '@D': 'Delta',
  '@e': 'epsilon', ':e': 'varepsilon', '@z': 'zeta', '@h': 'eta', '@t': 'theta', '@T': 'Theta',
  ':t': 'vartheta', '@i': 'iota', '@k': 'kappa', '@l': 'lambda', '@L': 'Lambda', '@m': 'mu',
  '@n': 'nu', '@x': 'xi', '@X': 'Xi', '@p': 'pi', '@P': 'Pi', '@r': 'rho', ':r': 'varrho',
  '@s': 'sigma', '@S': 'Sigma', '@u': 'upsilon', '@U': 'Upsilon', '@f': 'phi', '@F': 'Phi',
  ':f': 'varphi', '@c': 'chi', '@y': 'psi', '@Y': 'Psi', '@o': 'omega', '@O': 'Omega',
}

const GREEK = 'alpha|beta|gamma|Gamma|delta|Delta|epsilon|varepsilon|zeta|eta|theta|Theta|vartheta|iota|kappa|lambda|Lambda|mu|nu|xi|Xi|pi|Pi|rho|varrho|sigma|Sigma|tau|upsilon|Upsilon|phi|Phi|varphi|chi|psi|Psi|omega|Omega'
const SYMBOL = 'hbar|ell|nabla|infty|dots|leftrightarrow|mapsto|setminus|mid|bigcap|bigcup|cap|cup|land|lor|subseteq|subset|implies|impliedby|iff|exists|forall|equiv|square|neq|geq|leq|gg|ll|sim|simeq|approx|propto|cdot|oplus|otimes|times|star|perp|det|exp|ln|log|partial'
const FUNCS = 'arcsin|arccos|arctan|arccot|arccsc|arcsec|sinh|cosh|tanh|coth|sin|cos|tan|cot|csc|sec|min|max|sup|inf|log|ln|exp|det|dim|ker|deg|gcd|lim|arg|hom|Pr|Re|Im'

export const DEFAULT_SNIPPETS: Snippet[] = [
  // ---- Entering math ------------------------------------------------------
  { trigger: 'mk', replacement: '$$0$', options: 'tAw', description: 'inline math' },
  { trigger: 'dm', replacement: '$$\n$0\n$$', options: 'tAw', description: 'display math' },
  { trigger: 'beg', replacement: '\\begin{$0}\n$1\n\\end{$0}', options: 'mA' },

  // ---- Greek ----------------------------------------------------------------
  ...Object.entries(greek).map(([trigger, g]) => ({ trigger, replacement: '\\' + g, options: 'mA' })),
  { trigger: 'ome', replacement: '\\omega', options: 'mA' },

  // ---- Operators and symbols ------------------------------------------------
  { trigger: '...', replacement: '\\dots', options: 'mA' },
  { trigger: '=>', replacement: '\\implies', options: 'mA' },
  { trigger: '=<', replacement: '\\impliedby', options: 'mA' },
  { trigger: 'iff', replacement: '\\iff', options: 'mA' },
  { trigger: '!=', replacement: '\\neq', options: 'mA' },
  { trigger: '>=', replacement: '\\geq', options: 'mA' },
  { trigger: '<=', replacement: '\\leq', options: 'mA' },
  { trigger: '>>', replacement: '\\gg', options: 'mA' },
  { trigger: '<<', replacement: '\\ll', options: 'mA' },
  { trigger: '~~', replacement: '\\sim', options: 'mA' },
  { trigger: '\\sim~', replacement: '\\approx', options: 'mA' },
  { trigger: 'prop', replacement: '\\propto', options: 'mA' },
  { trigger: 'nabl', replacement: '\\nabla', options: 'mA' },
  { trigger: 'del', replacement: '\\nabla', options: 'mA' },
  { trigger: 'xx', replacement: '\\times', options: 'mA' },
  { trigger: '**', replacement: '\\cdot', options: 'mA' },
  { trigger: 'para', replacement: '\\parallel', options: 'mA' },
  { trigger: '->', replacement: '\\to', options: 'mA' },
  { trigger: '!>', replacement: '\\mapsto', options: 'mA' },
  { trigger: '<->', replacement: '\\leftrightarrow', options: 'mA' },
  { trigger: '\\to>', replacement: '\\longrightarrow', options: 'mA' },
  { trigger: '+-', replacement: '\\pm', options: 'mA' },
  { trigger: '-+', replacement: '\\mp', options: 'mA' },
  { trigger: 'oo', replacement: '\\infty', options: 'mA' },
  { trigger: 'OO', replacement: '\\emptyset', options: 'mA' },
  { trigger: 'AA', replacement: '\\forall', options: 'mA' },
  { trigger: 'EE', replacement: '\\exists', options: 'mA' },
  { trigger: 'inn', replacement: '\\in', options: 'mA' },
  { trigger: 'notin', replacement: '\\notin', options: 'mA' },
  { trigger: '\\\\\\', replacement: '\\setminus', options: 'mA' },
  { trigger: 'cc', replacement: '\\subset', options: 'mA' },
  { trigger: 'c=', replacement: '\\subseteq', options: 'mA' },
  { trigger: '\\subset=', replacement: '\\subseteq', options: 'mA' },
  { trigger: 'sup=', replacement: '\\supseteq', options: 'mA' },
  { trigger: 'cup', replacement: '\\cup', options: 'mA' },
  { trigger: 'cap', replacement: '\\cap', options: 'mA' },
  { trigger: 'UU', replacement: '\\bigcup', options: 'mA' },
  { trigger: 'Nn', replacement: '\\bigcap', options: 'mA' },
  { trigger: 'mid', replacement: '\\mid', options: 'mA' },
  { trigger: 'ell', replacement: '\\ell', options: 'mA' },
  { trigger: 'lll', replacement: '\\ell', options: 'mA' },
  { trigger: 'xnn', replacement: 'x_{n}', options: 'mA' },
  { trigger: 'xii', replacement: 'x_{i}', options: 'mA' },
  { trigger: 'xjj', replacement: 'x_{j}', options: 'mA' },
  { trigger: 'xp1', replacement: 'x_{n+1}', options: 'mA' },
  { trigger: 'ynn', replacement: 'y_{n}', options: 'mA' },
  { trigger: 'yii', replacement: 'y_{i}', options: 'mA' },
  { trigger: 'yjj', replacement: 'y_{j}', options: 'mA' },
  { trigger: 'ann', replacement: 'a_{n}', options: 'mA' },

  // ---- Fonts and sets -------------------------------------------------------
  { trigger: 'mcal', replacement: '\\mathcal{$0}$1', options: 'mA' },
  { trigger: 'mbb', replacement: '\\mathbb{$0}$1', options: 'mA' },
  { trigger: 'mfr', replacement: '\\mathfrak{$0}$1', options: 'mA' },
  { trigger: 'bf', replacement: '\\mathbf{$0}$1', options: 'mA' },
  { trigger: 'rm', replacement: '\\mathrm{$0}$1', options: 'mA' },
  { trigger: 'LL', replacement: '\\mathcal{L}', options: 'mA' },
  { trigger: 'HH', replacement: '\\mathcal{H}', options: 'mA' },
  { trigger: 'CC', replacement: '\\mathbb{C}', options: 'mA' },
  { trigger: 'RR', replacement: '\\mathbb{R}', options: 'mA' },
  { trigger: 'ZZ', replacement: '\\mathbb{Z}', options: 'mA' },
  { trigger: 'NN', replacement: '\\mathbb{N}', options: 'mA' },
  { trigger: 'QQ', replacement: '\\mathbb{Q}', options: 'mA' },
  { trigger: 'PP', replacement: '\\mathbb{P}', options: 'mA' },
  { trigger: 'FF', replacement: '\\mathbb{F}', options: 'mA' },
  { trigger: 'II', replacement: '\\mathbb{1}', options: 'mA' },
  { trigger: '"', replacement: '\\text{$0}$1', options: 'mA' },
  { trigger: 'sts', replacement: '_\\text{$0}', options: 'mA' },

  // ---- Powers, roots, fractions --------------------------------------------
  { trigger: 'sr', replacement: '^{2}', options: 'mA' },
  { trigger: 'cb', replacement: '^{3}', options: 'mA' },
  { trigger: 'rd', replacement: '^{$0}$1', options: 'mA' },
  { trigger: 'sq', replacement: '\\sqrt{ $0 }$1', options: 'mA' },
  { trigger: '//', replacement: '\\frac{$0}{$1}$2', options: 'mA' },
  { trigger: 'ee', replacement: 'e^{ $0 }$1', options: 'mA' },
  { trigger: 'invs', replacement: '^{-1}', options: 'mA' },
  { trigger: 'conj', replacement: '^{*}', options: 'mA' },
  { trigger: 'Re', replacement: '\\operatorname{Re}', options: 'mA' },
  { trigger: 'Im', replacement: '\\operatorname{Im}', options: 'mA' },

  // ---- Accents (regex: "xhat" -> \hat{x}, also on Greek letters) -----------
  { trigger: '([A-Za-z])hat', replacement: '\\hat{[[0]]}', options: 'rmA' },
  { trigger: '([A-Za-z])bar', replacement: '\\bar{[[0]]}', options: 'rmA' },
  { trigger: '([A-Za-z])vec', replacement: '\\vec{[[0]]}', options: 'rmA' },
  { trigger: '([A-Za-z])tilde', replacement: '\\tilde{[[0]]}', options: 'rmA' },
  { trigger: '([A-Za-z])dot', replacement: '\\dot{[[0]]}', options: 'rmA' },
  { trigger: '([A-Za-z])ddot', replacement: '\\ddot{[[0]]}', options: 'rmA', priority: 1 },
  { trigger: '([A-Za-z])und', replacement: '\\underline{[[0]]}', options: 'rmA' },
  { trigger: `\\\\(${GREEK})hat`, replacement: '\\hat{\\[[0]]}', options: 'rmA', priority: 2 },
  { trigger: `\\\\(${GREEK})bar`, replacement: '\\bar{\\[[0]]}', options: 'rmA', priority: 2 },
  { trigger: `\\\\(${GREEK})vec`, replacement: '\\vec{\\[[0]]}', options: 'rmA', priority: 2 },
  { trigger: `\\\\(${GREEK})tilde`, replacement: '\\tilde{\\[[0]]}', options: 'rmA', priority: 2 },
  { trigger: `\\\\(${GREEK})dot`, replacement: '\\dot{\\[[0]]}', options: 'rmA', priority: 2 },
  { trigger: 'hat', replacement: '\\hat{$0}$1', options: 'mA', priority: -1 },
  { trigger: 'bar', replacement: '\\bar{$0}$1', options: 'mA', priority: -1 },
  { trigger: 'vec', replacement: '\\vec{$0}$1', options: 'mA', priority: -1 },
  { trigger: 'tilde', replacement: '\\tilde{$0}$1', options: 'mA', priority: -1 },
  { trigger: 'dot', replacement: '\\dot{$0}$1', options: 'mA', priority: -1 },

  // ---- Functions: "sin" -> \sin, but not inside a macro name -----------------
  { trigger: `(^|[^\\\\A-Za-z])(${FUNCS})`, replacement: '[[0]]\\[[1]]', options: 'rmA', priority: -2 },
  { trigger: `(^|[^\\\\A-Za-z])(${SYMBOL})`, replacement: '[[0]]\\[[1]]', options: 'rmA', priority: -3 },

  // ---- Big operators ---------------------------------------------------------
  { trigger: 'sum', replacement: '\\sum', options: 'mA' },
  { trigger: '\\sum', replacement: '\\sum_{${0:n}=${1:1}}^{${2:\\infty}} $3', options: 'm' },
  { trigger: 'prod', replacement: '\\prod', options: 'mA' },
  { trigger: '\\prod', replacement: '\\prod_{${0:n}=${1:1}}^{${2:\\infty}} $3', options: 'm' },
  { trigger: 'lim', replacement: '\\lim', options: 'mA' },
  { trigger: '\\lim', replacement: '\\lim_{ ${0:n} \\to ${1:\\infty} } $2', options: 'm' },
  { trigger: 'limsup', replacement: '\\limsup_{ ${0:n} \\to ${1:\\infty} } $2', options: 'mA', priority: 1 },
  { trigger: 'liminf', replacement: '\\liminf_{ ${0:n} \\to ${1:\\infty} } $2', options: 'mA', priority: 1 },
  { trigger: 'int', replacement: '\\int', options: 'mA' },
  { trigger: '\\int', replacement: '\\int_{ ${0:a} }^{ ${1:b} } $2 \\, d${3:x} $4', options: 'm' },
  { trigger: 'dint', replacement: '\\int_{ ${0:a} }^{ ${1:b} } $2 \\, d${3:x} $4', options: 'mA' },
  { trigger: 'oinf', replacement: '\\int_{0}^{\\infty} $0 \\, d${1:x} $2', options: 'mA' },
  { trigger: 'infi', replacement: '\\int_{-\\infty}^{\\infty} $0 \\, d${1:x} $2', options: 'mA' },
  { trigger: 'oint', replacement: '\\oint', options: 'mA' },
  { trigger: 'iint', replacement: '\\iint', options: 'mA' },
  { trigger: 'iiint', replacement: '\\iiint', options: 'mA' },
  { trigger: 'par', replacement: '\\frac{ \\partial $0 }{ \\partial $1 } $2', options: 'mA' },
  { trigger: 'dd', replacement: '\\frac{ d$0 }{ d$1 } $2', options: 'mA' },
  { trigger: 'ddt', replacement: '\\frac{d}{dt} ', options: 'mA', priority: 1 },

  // ---- Delimiters ------------------------------------------------------------
  { trigger: 'lr(', replacement: '\\left( $0 \\right) $1', options: 'mA' },
  { trigger: 'lr|', replacement: '\\left| $0 \\right| $1', options: 'mA' },
  { trigger: 'lr{', replacement: '\\left\\{ $0 \\right\\} $1', options: 'mA' },
  { trigger: 'lr[', replacement: '\\left[ $0 \\right] $1', options: 'mA' },
  { trigger: 'lra', replacement: '\\left< $0 \\right> $1', options: 'mA' },
  { trigger: 'abs', replacement: '\\left| $0 \\right| $1', options: 'mA' },
  { trigger: 'norm', replacement: '\\left\\| $0 \\right\\| $1', options: 'mA' },
  { trigger: 'ceil', replacement: '\\left\\lceil $0 \\right\\rceil $1', options: 'mA' },
  { trigger: 'floor', replacement: '\\left\\lfloor $0 \\right\\rfloor $1', options: 'mA' },
  { trigger: 'set', replacement: '\\{ $0 \\} $1', options: 'mA' },
  { trigger: 'avg', replacement: '\\langle $0 \\rangle $1', options: 'mA' },

  // ---- Environments inside math ---------------------------------------------
  { trigger: 'pmat', replacement: '\\begin{pmatrix}\n$0\n\\end{pmatrix}', options: 'mA' },
  { trigger: 'bmat', replacement: '\\begin{bmatrix}\n$0\n\\end{bmatrix}', options: 'mA' },
  { trigger: 'Bmat', replacement: '\\begin{Bmatrix}\n$0\n\\end{Bmatrix}', options: 'mA' },
  { trigger: 'vmat', replacement: '\\begin{vmatrix}\n$0\n\\end{vmatrix}', options: 'mA' },
  { trigger: 'matrix', replacement: '\\begin{matrix}\n$0\n\\end{matrix}', options: 'mA' },
  { trigger: 'cases', replacement: '\\begin{cases}\n$0\n\\end{cases}', options: 'mA' },
  { trigger: 'align', replacement: '\\begin{aligned}\n$0\n\\end{aligned}', options: 'mA' },
  { trigger: 'array', replacement: '\\begin{array}{${0:cc}}\n$1\n\\end{array}', options: 'mA' },

  // ---- Visual snippets (select text, press the key) --------------------------
  { trigger: 'U', replacement: '\\underbrace{ ${VISUAL} }_{ $0 }', options: 'mv' },
  { trigger: 'O', replacement: '\\overbrace{ ${VISUAL} }^{ $0 }', options: 'mv' },
  { trigger: 'B', replacement: '\\underset{ $0 }{ ${VISUAL} }', options: 'mv' },
  { trigger: 'C', replacement: '\\cancel{ ${VISUAL} }', options: 'mv' },
  { trigger: 'K', replacement: '\\cancelto{ $0 }{ ${VISUAL} }', options: 'mv' },
  { trigger: 'S', replacement: '\\sqrt{ ${VISUAL} }', options: 'mv' },
  { trigger: 'F', replacement: '\\frac{ ${VISUAL} }{ $0 }', options: 'mv' },
  { trigger: 'P', replacement: '\\left( ${VISUAL} \\right)', options: 'mv' },
  { trigger: 'T', replacement: '\\text{ ${VISUAL} }', options: 'mv' },
  { trigger: 'M', replacement: '$${VISUAL}$', options: 'tv' },
  { trigger: 'E', replacement: '\\emph{${VISUAL}}', options: 'tv' },
  { trigger: 'B', replacement: '\\textbf{${VISUAL}}', options: 'tv' },

  // ====================================================================
  //  mathbook class snippets (text mode).  All start with ";" so they
  //  never fire inside ordinary prose.  Tabstops: Tab / Shift-Tab.
  // ====================================================================
  { trigger: ';thm', replacement: '\\begin{theorem}[${0:}]\\label{thm:${1:key}}\n  $2\n\\end{theorem}', options: 'tA', description: 'theorem' },
  { trigger: ';lem', replacement: '\\begin{lemma}[${0:}]\\label{lem:${1:key}}\n  $2\n\\end{lemma}', options: 'tA', description: 'lemma' },
  { trigger: ';prop', replacement: '\\begin{proposition}[${0:}]\\label{prop:${1:key}}\n  $2\n\\end{proposition}', options: 'tA', description: 'proposition' },
  { trigger: ';cor', replacement: '\\begin{corollary}[${0:}]\\label{cor:${1:key}}\n  $2\n\\end{corollary}', options: 'tA', description: 'corollary' },
  { trigger: ';clm', replacement: '\\begin{claim}\n  $0\n\\end{claim}', options: 'tA', description: 'claim' },
  { trigger: ';def', replacement: '\\begin{definition}[${0:}]\\label{def:${1:key}}\n  $2\n\\end{definition}', options: 'tA', description: 'definition' },
  { trigger: ';exm', replacement: '\\begin{example}[${0:}]\\label{ex:${1:key}}\n  $2\n\\end{example}', options: 'tA', description: 'example' },
  { trigger: ';rmk', replacement: '\\begin{remark}\n  $0\n\\end{remark}', options: 'tA', description: 'remark' },
  { trigger: ';not', replacement: '\\begin{notation}\n  $0\n\\end{notation}', options: 'tA', description: 'notation' },
  { trigger: ';prf', replacement: '\\begin{proof}\n  $0\n\\end{proof}', options: 'tA', description: 'proof' },
  { trigger: ';exs', replacement: '\\begin{exercises}\n\\begin{exercise}\\label{exr:${0:key}}\n  $1\n\\end{exercise}\n\\end{exercises}', options: 'tA', description: 'exercises block' },
  { trigger: ';exr', replacement: '\\begin{exercise}\\label{exr:${0:key}}\n  $1\n\\end{exercise}', options: 'tA', description: 'exercise' },
  { trigger: ';exh', replacement: '\\begin{exercise*}\\label{exr:${0:key}}\n  $1\n\\end{exercise*}', options: 'tA', description: 'harder exercise (starred)' },
  { trigger: ';prbs', replacement: '\\begin{problems}\n\\begin{problem}[${0:}]\\label{prob:${1:key}}\n  $2\n\\end{problem}\n\\end{problems}', options: 'tA', description: 'end-of-chapter problems' },
  { trigger: ';prb', replacement: '\\begin{problem}[${0:}]\\label{prob:${1:key}}\n  $2\n\\end{problem}', options: 'tA', description: 'problem' },
  { trigger: ';prh', replacement: '\\begin{problem*}\\label{prob:${0:key}}\n  $1\n\\end{problem*}', options: 'tA', description: 'harder problem' },
  { trigger: ';hint', replacement: '\\hint{$0}', options: 'tA', description: '[Hint: ...]' },
  { trigger: ';ft', replacement: '\\fromtext{$0}', options: 'tA', description: 'exercise referred to from the text (▷)' },
  { trigger: ';fe', replacement: '\\fromex{$0}', options: 'tA', description: 'exercise referred to from other exercises (¬)' },
  { trigger: ';parts', replacement: '\\begin{parts}\n  \\item $0\n\\end{parts}', options: 'tA', description: '(a), (b), ... parts' },
  { trigger: ';chap', replacement: '\\chapter{${0:Title}}\\label{ch:${1:key}}\n\\chapterquote{${2:Quote}}{${3:Author}}{${4:Source}}\n\n$5', options: 'tA', description: 'chapter with epigraph' },
  { trigger: ';sec', replacement: '\\section{${0:Title}}\\label{sec:${1:key}}\n\n$2', options: 'tA', description: 'section' },
  { trigger: ';ssec', replacement: '\\subsection{${0:Title}}\n$1', options: 'tA', description: 'subsection' },
  { trigger: ';proc', replacement: '\\begin{procedure}[returns=${0:\\N}, caption={${1:}}, label=alg:${2:key}]\n  {${3:Name}}{${4:A: \\R^n, n: \\N}}\n  \\State $5\n\\end{procedure}', options: 'tA', description: 'CLRS-style procedure' },
  { trigger: ';cols', replacement: '\\Cols{$0 & $1}', options: 'tA', description: 'cost/times columns entry' },
  { trigger: ';fig', replacement: '\\begin{figure}[${0:tbp}]\n  \\centering\n  \\includegraphics[width=${1:0.6}\\textwidth]{figures/${2:name}}\n  \\caption{${3:}}\n  \\label{fig:${4:key}}\n\\end{figure}', options: 'tA', description: 'figure' },
  { trigger: ';fn', replacement: '\\footnote{$0}', options: 'tA', description: 'footnote' },
  { trigger: ';ref', replacement: '\\cref{$0}', options: 'tA', description: 'cross reference' },
  { trigger: ';Ref', replacement: '\\Cref{$0}', options: 'tA', description: 'cross reference (sentence start)' },
  { trigger: ';eq', replacement: '\\begin{equation}\\label{eq:${0:key}}\n  $1\n\\end{equation}', options: 'tA', description: 'numbered equation' },
  { trigger: ';al', replacement: '\\begin{align}\n  $0\n\\end{align}', options: 'tA', description: 'align' },
  { trigger: ';al*', replacement: '\\begin{align*}\n  $0\n\\end{align*}', options: 'tA', description: 'align*' },
  { trigger: ';it', replacement: '\\begin{itemize}\n  \\item $0\n\\end{itemize}', options: 'tA', description: 'itemize' },
  { trigger: ';en', replacement: '\\begin{enumerate}\n  \\item $0\n\\end{enumerate}', options: 'tA', description: 'enumerate' },
  { trigger: ';em', replacement: '\\emph{$0}', options: 'tA', description: 'emphasis' },
  { trigger: ';bf', replacement: '\\textbf{$0}', options: 'tA', description: 'bold' },
]

export const MATH_MODE_KEYWORDS = { GREEK, SYMBOL, FUNCS }
